#!/bin/bash
# *********************************************************************** #
# author: fmarcos83                                                       #
# email : fmarcos83@gmail.com                                             #
# An easy and dirty fast way to have a bookmark system                    #
# *********************************************************************** #

# TODO: add autocompletion
# TODO: I don't like g option, should change to bookmark
#       on bm $bookmark
bookmarkfolder=~/.bookmarks
usage="\n
       Very simple bookmark system:\n
       c) creates a bookmark on the current directory\n
       d) removes a bookmark\n
       l) list bookmarks in the system\n
       n) napalm removes every missing bookmark\n
       g) changes directory to the bookmark\n"
while getopts 'lnc:d:g:h' OPTION;
do
    case $OPTION in
        # create the bookmark
        # TODO: necesary to check if the bookmark already exists
        #       before creating it
        c)
            bookmarkname="$OPTARG"
           if [[ ! -e $bookmarkfolder ]]; then
               mkdir $bookmarkfolder
           fi
           # adding the bookmark
           ln -s $(pwd) $bookmarkfolder/$bookmarkname
           ;;
        # deletes the bookmark
        d)
           bookmarkname="$OPTARG"
           rm $bookmarkfolder/$bookmarkname
           ;;
        # lists all the bookmarks
        l)
           ls $bookmarkfolder/ --color -1
           OPTION='l'
           ;;
        # go to bookmark
        g)
           bookmarkname=$OPTARG;
           # resolving the symbolic link
           dir=$(readlink $bookmarkfolder/$bookmarkname)
           cd $dir/
           ;;
        n)
           find $bookmarkfolder/ -xtype l -exec rm {} -rf \;
           ;;
        h)
           echo -e $usage
           ;;
        ?)
           echo -e $usage
           ;;
    esac
done
