#!/bin/bash
# *********************************************************************** #
# author: fmarcos83                                                       #
# email : fmarcos83@gmail.com                                             #
# An easy and dirty fast way to have a bookmark system                    #
# *********************************************************************** #

# TODO: add autocompletion
# TODO: I don't like g option, should change to bookmark
#       on bm $bookmark
function bm(){
bookmarkfolder=~/.bookmarks
#sanity check to create bookmark file if it doesn't exist yet
if [[ ! -e $bookmarkfolder ]]; then
   mkdir $bookmarkfolder
fi

OPTIND=1
while getopts 'lc:d:g:' OPTION;
do
    case $OPTION in
        # create the bookmark
        # TODO: necesary to check if the bookmark already exists
        #       before creating it
        c)
            bookmarkname="$OPTARG"
        # adding the bookmark
           ln -s $(pwd) $bookmarkfolder/$bookmarkname
           ;;
        # deletes the bookmark
        d)
           bookmarkname="$OPTARG"
           rm $bookmarkfolder/$bookmarkname
           ;;
        # lists all the bookmarks
        l)
           ls $bookmarkfolder/ --color -1
           OPTION='l'
           ;;
        # go to bookmark
        g)
           bookmarkname=$OPTARG;
           # resolving the symbolic link
           dir=$(readlink $bookmarkfolder/$bookmarkname)
           cd $dir/
           ;;
        ?)
           echo "Very simple bookmark system:"
           echo "c) creates a bookmark on the current directory"
           echo "d) removes a bookmark"
           echo "l) list bookmarks in the system"
           echo "g) changes directory to the bookmark"
           ;;

    esac
done
}
