#!/bin/bash
dir=$( git rev-parse --show-toplevel );
publicjs="$dir/public/js/application"
cfpath="/home/fmarcos83/workspace/external/scripts/jshinttrailingcommanscf"
find $publicjs -name '*js' | xargs -I file jshint -c $cfpath file | grep 'Extra comma'
