#!/bin/bash
dir=$( git rev-parse --show-toplevel );
publicjs="$dir/public/js"
cfpath="/home/fmarcos83/workspace/external/scripts/jshinttrailingcommanscf"
find $publicjs "$publicjs/library/3rd" -prune -o -name '*js' | xargs -I file jshint -c $cfpath file | grep 'Extra comma'
