#! /bin/bash
expresionDefault="/js/data.*json";
pathSearch=$1;
expression=$2;
if [ -z $pathSearch ]; then
    pathSearch="$(pwd)/public/js";
fi
if [ -z $expression ]; then
    expression=$expresionDefault;
fi
numwrongFiles=$(grep $expression $pathSearch -l --exclude-dir='public/js/tests' | wc -l)
if [ $numwrongFiles -gt 0 ]; then
    files=$(grep $expression $pathSearch -l --exclude-dir='public/js/tests')
    echo -e "
        It seems you have mock data review the following files:

        $files
    "
    exit 1;
fi
exit 0;
